version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: market-db
    environment:
      POSTGRES_DB: market_data
      POSTGRES_USER: student
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U student -d market_data"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - market-net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: market-rabbitmq
    ports:
      - "5672:5672"   # Portul de mesagerie
      - "15672:15672" # Interfata vizuala (Dashboard)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - market-net

  gateway:
    build: ./gateway-java
    container_name: java-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/market_data
      SPRING_DATASOURCE_USERNAME: student
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      GROQ_API_KEY: ${GROQ_API_KEY}
      # Configurare RabbitMQ pentru Java
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - market-net

  aggregator:
    build: ./aggregator-rust
    container_name: rust-aggregator
    environment:
      RABBITMQ_ADDR: amqp://guest:guest@rabbitmq:5672/%2f
    depends_on:
      - gateway
      - rabbitmq
    networks:
      - market-net

volumes:
  postgres_data:

networks:
  market-net:
    driver: bridge