version: '3.8'

services:
  # 1. Baza de date
  postgres:
    image: postgres:15-alpine
    container_name: market-db
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: secretpassword123
      POSTGRES_DB: market_data
    ports:
      - "5432:5432"
    healthcheck:
      # Aici era problema! Acum scriem explicit userul 'student'
      test: ["CMD-SHELL", "pg_isready -U student -d market_data"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Java Gateway
  java-gateway:
    build: ./gateway-java
    container_name: java-gateway
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: secretpassword123
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/market_data
    depends_on:
      postgres:
        condition: service_healthy

  # 3. Rust Aggregator
  rust-aggregator:
    build: ./aggregator-rust
    container_name: rust-aggregator
    depends_on:
      - java-gateway